services:
  localstack:
    container_name: "aws-local"
    image: localstack/localstack
    env_file:
      - .env
    ports:
      - "${AWS_PORT}:${AWS_PORT}"
    environment:
      - DEFAULT_REGION=${AWS_REGION}
      - DOCKER_HOST=unix:///var/run/docker
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_SECRET}
      - SERVICES=${AWS_SERVICES}
    volumes:
      - ./localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
